from typing import Any, Dict

from core.gateway import GovernanceGateway
from models.schemas import ActionRequest


class BehaviorGateway:
    """
    Converts observed AI behavior into governance actions.

    This layer does NOT make security decisions.
    It only captures/normalizes behavior and sends it
    to the existing GovernanceGateway.
    """

    def __init__(self, gateway: GovernanceGateway):
        self.gateway = gateway

    # ======================================================
    # INGEST OBSERVED AI BEHAVIOR
    # ======================================================

    def ingest(
        self,
        request_id: str,
        agent_id: str,
        role: str,
        tool: str,
        resource: str = None,
        parameters: Dict[str, Any] = None,
    ):

        action_request = ActionRequest(
            action_id=f"ACT-{request_id}",
            request_id=request_id,
            agent_id=agent_id,
            tool=tool,
            resource=resource,
            parameters=parameters or {},
        )

        return self.gateway.process_action(
            action_request=action_request,
            role=role,
        )

    # ======================================================
    # DEMO BEHAVIOR SCENARIOS
    # ======================================================

    def list_scenarios(self):

        return [
            {
                "id": "safe_read",
                "name": "Research Agent",
                "description": "Agent attempts to read a permitted file.",
                "agent_id": "research-agent",
                "role": "AGENT",
                "tool": "read_file",
                "resource": "demo.txt",
                "parameters": {},
            },
            {
                "id": "dangerous_command",
                "name": "System Agent",
                "description": "Agent attempts to execute a system command.",
                "agent_id": "system-agent",
                "role": "AGENT",
                "tool": "execute_command",
                "resource": "system",
                "parameters": {
                    "command": "whoami"
                },
            },
            {
                "id": "file_write",
                "name": "Report Agent",
                "description": "Agent attempts to write a report file.",
                "agent_id": "report-agent",
                "role": "ADMIN",
                "tool": "write_file",
                "resource": "behavior_report.txt",
                "parameters": {
                    "content": "Generated by Report Agent."
                },
            },
        ]

    # ======================================================
    # RUN DEMO BEHAVIOR
    # ======================================================

    def run_demo(self, scenario_id: str):

        scenario = None

        for item in self.list_scenarios():

            if item["id"] == scenario_id:
                scenario = item
                break

        if scenario is None:
            raise ValueError(
                f"Unknown behavior scenario: {scenario_id}"
            )

        result = self.ingest(
            request_id=(
                f"BEHAVIOR-{scenario_id.upper()}"
            ),
            agent_id=scenario["agent_id"],
            role=scenario["role"],
            tool=scenario["tool"],
            resource=scenario["resource"],
            parameters=scenario["parameters"],
        )

        return {
            "source": "AI_BEHAVIOR",
            "scenario": scenario,
            "governance": result,
        }